version: '3.8'

services:
  database:
    image: mongo:latest
    container_name: mongodb_prod
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: mern_backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://database:27017/tasks
    depends_on:
      - database

  frontend:
    build: ./frontend
    container_name: mern_frontend
    ports:
      - "80:80"
    # This allows the frontend to talk to the backend container
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api/tasks
    depends_on:
      - backend

volumes:
  mongo-data: